branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\Tools\mingw730_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake I2P-Messenger.pro
  - mingw32-make
after_build:
  - windeployqt release/I2P-Messenger.exe
  - cmd: cp LICENSE release/LICENSE.txt"

artifacts:
  - path: Output\I2P-Messenger-*.exe
  - path: release
    type: zip
